language: cpp
sudo: true
compiler:
- gcc
before_install:
- git submodule update --init --recursive
install:
- sudo apt install -y automake autoconf
script:
- MBEDTLS_VER=2.6.0
- PCRE_VER=8.40
- LIBEV_VER=4.24
- LIBSODIUM_VER=1.0.12
- BUILDROOT=`pwd`
- JOBS=`nproc`
- wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz -O - | tar xzf -
  -C .
- wget https://ftp.pcre.org/pub/pcre/pcre-$PCRE_VER.tar.gz -O - | tar xzf - -C .
- wget https://download.libsodium.org/libsodium/releases/libsodium-$LIBSODIUM_VER.tar.gz
  -O - | tar xzf - -C .
- wget http://dist.schmorp.de/libev/libev-$LIBEV_VER.tar.gz -O -|tar xzf - -C .
- git clone https://github.com/shadowsocks/libudns
- git clone https://github.com/shadowsocks/shadowsocks-libev
- git clone https://github.com/shadowsocks/simple-obfs
- pushd mbedtls-$MBEDTLS_VER
- sed -i "s#DESTDIR=\/usr\/local#DESTDIR=$BUILDROOT\/dists\/mbedtls#g" Makefile
- LDFLAGS=-static make -j$JOBS install
- popd
- pushd pcre-$PCRE_VER
- "./configure --prefix=$BUILDROOT/dists/pcre --disable-shared --enable-utf8 --enable-unicode-properties"
- make -j$JOBS install
- popd
- pushd libev-$LIBEV_VER
- "./configure --prefix=$BUILDROOT/dists/libev --disable-shared"
- make -j$JOBS install
- popd
- pushd libsodium-$LIBSODIUM_VER
- "./configure --prefix=$BUILDROOT/dists/libsodium --disable-shared --disable-ssp"
- make -j$JOBS install
- popd
- pushd libudns
- "./autogen.sh"
- "./configure --prefix=$BUILDROOT/dists/libudns"
- make -j$JOBS install
- popd
- pushd shadowsocks-libev
- git submodule init && git submodule update
- "./autogen.sh"
- LIBS="-lpthread -lm" LDFLAGS="-Wl,-static -static -static-libgcc -L$BUILDROOT/dists/libudns/lib
  -L$BUILDROOT/dists/libev/lib" CFLAGS="-I$BUILDROOT/dists/libudns/include -I$BUILDROOT/dists/libev/include"
  ./configure --prefix=$BUILDROOT/dists/shadowsocks-libev --disable-ssp --disable-documentation
  --with-mbedtls=$BUILDROOT/dists/mbedtls --with-pcre=$BUILDROOT/dists/pcre --with-sodium=$BUILDROOT/dists/libsodium
- make -j$JOBS install
- popd
- pushd simple-obfs
- git submodule init && git submodule update
- "./autogen.sh"
- LIBS="-lpthread -lm" LDFLAGS="-Wl,-static -static -static-libgcc -L$BUILDROOT/dists/libsodium/lib
  -L$BUILDROOT/dists/libudns/lib -L$BUILDROOT/dists/libev/lib" CFLAGS="-I$BUILDROOT/dists/libsodium/include
  -I$BUILDROOT/dists/libudns/include -I$BUILDROOT/dists/libev/include" ./configure  --prefix=$BUILDROOT/dists/shadowsocks-libev
  --disable-ssp --disable-documentation
- make -j$JOBS install
- popd
after_success:
- cp dists/shadowsocks-libev/bin shadowsocks-libev-static -r
- tar czf shadowsocks-libev-static.tar.gz shadowsocks-libev-static
- BRANCH="master"
- if [ "$TRAVIS_BRANCH" = "$BRANCH" ]; then
- if [ "$TRAVIS_PULL_REQUEST" = false ]; then
- if [ -z "$TRAVIS_TAG" ]; then
- echo -e "Starting to tag commit.\n"
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis"
- git tag -a v${TRAVIS_BUILD_NUMBER} -m "Travis build $TRAVIS_BUILD_NUMBER pushed
  a tag."
- git push origin --tags
- git fetch origin
- echo -e "Done magic with tags.\n"
- fi
- fi
- fi
deploy:
  provider: releases
  file: shadowsocks-libev-static.tar.gz
  skip_cleanup: true
  on:
    branch: master
    repo: ReinForce-II/shadowsocks-libev-static
  api-key:
    secure: K++uo15GeXFPGQKgNx85KEhNVRThpLUP3xO51TR4kZq+3RVq6338SV9ZvpIJRHVDcvan5CDBY77Uwzsbw+E2Xmu+r1DeKt3CnXVWHJ/9Yp5j8BHP571WCjjIffIVP4JQ/Rk2VmHP1sxpwK0fpPwRuEwCzRjdTGE5IS0GHmXImVDTtT9Ulg1n/PDeWdMyUm8HlT7o9WVMaSnbHj0TzAJ0guOaY4+ym8k4vgNMNv+CWA9PAMtXFOwtN05RMIOKQx6vkdDZQvMb5b7MnY5rPFRPN2oOwndHRhVtFAB+PGSM3uk5ii95KWdZytTR06B0eOfh+LB9Nhsy/FBzh69G9t1owMXJqR+rs6HZTvv7TBGCwu0g+0Zpojxq3FdEv9E8+01XpkZFVzBh4ka2kZtfd1WO/VwgOrsl2NDj74+mpbj1cjkf13rZ/LXK+c0taWb051q3JuJR0fK78oq9es0vlj+uTCcqeHmL6JG9eyYcxLQMP2QmnoYjtvhOhCfMb7aPrnyOYY90gEcN29Rxss0YI29s5dE5MUtSMKa0D3HX0w9sBTEzm67wzkTlwDhYGnUQ9UP1pzyhSeU9jvLIAwoaHKti+ubJij6CNsUokAQNloy4yoJsuXwuJ4y75tGAS5c6rsFDJiZ75+TF5QADn/G050V6a1/8DGajcORY7fGi7Ab1oDQ=
